import { use } from "react"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode,
  params: Promise<{locale: string}>
}) {
  const {locale} = use(params)
  return (
    <html lang={locale}>
      <body>{children}</body>
    </html>
  )
}
